homeassistant:
  customize: !include customize.yaml
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  time_zone: America/Chicago

device_tracker:
  - platform: ping
    hosts:
      carl_pixel2: !secret ip_pixel2xl
      maggie_pixel3: !secret ip_pixel3a
  - platform: bluetooth_tracker
    interval_seconds: 30
    new_device_defaults:
      track_new_devices: false
#  - platform: bluetooth_le_tracker
#    new_device_defaults:
#      track_new_devices: false
#      hide_if_away: false

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1
  platform: tuya

pi_hole:
  - host: !secret ip_raspberry_pi_pihole
    name: 'Main Pi Hole'

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: US
  devices:
    - device_id: !secret dyson_device_id
      device_ip: !secret ip_dyson

roku:
  - host: !secret ip_roku

lovelace:
  mode: yaml

camera:
  - platform: generic
    still_image_url: https://s.w-x.co/staticmaps/wu/wu/wxtype1200_cur/usspi/current.png
    name: Radar IL Current

airvisual:
  api_key: !secret air_visual_key
  geographies:
    #latitude: !secret latitude
    #longitude: !secret longitude
    city: Chicago
    state: Illinois
    country: USA

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: processor_use
      - type: last_boot
      - type: memory_use_percent
      - type: swap_free
      - type: swap_use_percent
  #- platform: airvisual
#    api_key: !secret air_visual_key
    #monitored_conditions:
    #  - us
    #show_on_map: false
    #scan_interval: 300
#    geographies:
      #latitude: !secret latitude
      #longitude: !secret longitude
#      city: Chicago
#      state: Illinois
#      country: USA
  - platform: miflora
    mac: 'C4:7C:8D:66:D7:87'
    name: Flower 1
    force_update: true
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:66:D7:A9'
    name: Flower 2
    force_update: true
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery

binary_sensor:
  - platform: template
    sensors:
      show_dyson:
        friendly_name: Dyson API up
        value_template: >-
          {{
          is_state('fan.master_bedroom', 'off')
            or
          is_state('fan.master_bedroom', 'on')
          }}
  - platform: template
    sensors:
      everybody_home:
        friendly_name: Everybody Home
        value_template: >-
          {{
          is_state('person.maggie', 'home')
            and
          is_state('person.carl', 'home')
          }}
  - platform: template
    sensors:
      anybody_home:
        friendly_name: Anybody Home
        value_template: >-
          {{
          is_state('person.maggie', 'home')
            or
          is_state('person.carl', 'home')
          }}
  - platform: ping
    name: Nas LS420D
    host: !secret ip_nas
    count: 2
    scan_interval: 60
  - platform: ping
    name: Raspberry Pi - Pi-hole
    host: !secret ip_raspberry_pi_pihole
    count: 2
    scan_interval: 60
  - platform: ping
    name: Raspberry Pi - PiVPN
    host: !secret ip_raspberry_pi_pivpn
    count: 2
    scan_interval: 60
  - platform: ping
    name: Roku
    host: !secret ip_roku
    count: 2
    scan_interval: 60
  - platform: ping
    name: Google Home
    host: !secret ip_google_home
    count: 2
    scan_interval: 60
  - platform: ping
    name: Chromecast
    host: !secret ip_chromecast
    count: 2
    scan_interval: 60
  - platform: ping
    name: Dyson fan
    host: !secret ip_dyson
    count: 2
    scan_interval: 60

frontend:
  themes: !include_dir_merge_named themes/

zwave:
 usb_path: /dev/ttyUSB0

zha:
 usb_path: /dev/ttyUSB1
 database_path: /config/zigbee.db

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
