title: Home Assistant
resources:
  - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.9.1
    type: module
    
views:
  - icon: mdi:home
    path: default_view
    title: Home
#    badges:
#      - entity: person.carl
#      - entity: person.maggie
    cards:
      # Weather card
      - type: custom:weather-card
        entity: weather.dark_sky
        name: Chicago
      # Illinois card
      - type: picture-glance
        camera_image: camera.radar_il_current
        entities:
          - camera.radar_il_current
       # Family card
      - type: entities
        title: Family
        show_header_toggle: false
        entities:
          - entity: person.maggie
          - entity: person.carl
      # Lights card
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - entity: switch.02200059ecfabc849dc9
          - entity: light.hue_ambiance_lamp_1
      # HUE card
      - type: light
        name: Hue lamp
        entity: light.hue_ambiance_lamp_1
      # Bedroom card, around dyson sensors
      - type: conditional
        conditions:
          - entity: binary_sensor.show_dyson
            state: "on"
        card:
          type: entities
          show_header_toggle: false
          title: Bedroom
          entities:
          - entity: sensor.master_bedroom_temperature
          - entity: sensor.master_bedroom_humidity
          - entity: sensor.master_bedroom_aqi
          - entity: sensor.master_bedroom_dust
          - entity: fan.master_bedroom
          - entity: sensor.master_bedroom_filter_life

  - icon: mdi:play-network
    cards:
      - entity: media_player.roku_yf00ec953393
        type: media-control
      - entity: media_player.living_room_speaker
        type: media-control
      - entity: media_player.chromecarlst
        type: media-control
  
  - icon: mdi:server-network
    cards:
      - title: Devices
        type: entities
        show_header_toggle: false
        entities:
          - entity: device_tracker.carl_pixel2
          - entity: device_tracker.maggie_pixel3
          - entity: binary_sensor.nas_ls420d
          - entity: binary_sensor.raspberry_pi_pi_hole
          - entity: binary_sensor.raspberry_pi_pivpn
          - entity: binary_sensor.roku
          - entity: binary_sensor.chromecast
          - entity: binary_sensor.google_home
          - entity: binary_sensor.dyson_fan

  - icon: mdi:settings
    cards:
      - type: entities
        title: Home Assistant Stats
        show_header_toggle: false
        entities:
          - entity: sensor.processor_use
          - entity: sensor.memory_use_percent
          - entity: sensor.disk_use_percent
          - entity: sensor.swap_use_percent
          - entity: sensor.last_boot
      - type: custom:mini-graph-card
        name: Processor
        entities:
          - sensor.processor_use
      - type: custom:mini-graph-card
        name: Memory
        entities:
          - sensor.memory_use_percent
      - entities:
          - entity: sensor.main_pi_hole_ads_blocked_today
          - entity: sensor.main_pi_hole_ads_percentage_blocked_today
        show_header_toggle: false
        title: Pi-hole
        type: entities
        
  - icon: mdi:alert-rhombus
    cards:
      - type: conditional
        conditions:
          - entity: binary_sensor.show_dyson
            state: "off"
        card:
          type: entities
          show_header_toggle: false
          title: Bedroom
          entities:
          - entity: sensor.master_bedroom_temperature
          - entity: sensor.master_bedroom_humidity
          - entity: sensor.master_bedroom_aqi
          - entity: sensor.master_bedroom_dust
          - entity: fan.master_bedroom
          - entity: sensor.master_bedroom_filter_life

